[package]
name = "faerie_rust"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.94"
cxx = "1.0.133"
wasmtime = "27.0.0"

[build-dependencies]
cxx-build = "1.0"
